name: Build "turnip"

on:
  workflow_dispatch:

jobs:
  start_building_turnip:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3

    - name: Prepare environment
      run: |
        sudo sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
        sudo apt update
        sudo apt build-dep mesa -y

    - name: Execute build script
      run: bash ./turnip_builder.sh

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Upload meson and ninja logs for debugging
        path:  |
          turnip_workdir/mesa-25.0.1/build-android-aarch64/meson-logs/meson-log.txt

    - name: Release "turnip"
      uses: softprops/action-gh-release@v1
      with:
        body: Turnip build for android
        tag_name: Turnip
        name: Release
        files: |
           turnip_workdir/mesa-25.0.1/build-android-aarch64/src/freedreno/vulkan/libvulkan_freedreno.so 
